### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shnick**

### CODE REVIEW

**Comment by platops-pr-bot-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See confluence https://confluence.tools.tax.service.gov.uk/x/9oH1FQ

**Comment by platops-pr-bot-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180

**Comment by platops-pr-bot-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- Please update Dependency(uk.gov.hmrc,bootstrap-frontend-play-28,5.20.0,Some(compile)) in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) to 5.21.0 - <bobbyMessage>

**Comment by platops-pr-bot-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be upgraded to `5.21.0` - <bobbyMessage>

**Comment by platops-pr-bot-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be upgraded to `5.21.0`
- `uk.gov.hmrc.bootstrap-common-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be changed to test scope - for security

**Comment by platops-general-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be upgraded to `5.21.0`
- `uk.gov.hmrc.bootstrap-common-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be changed to test scope - for security

**Comment by platops-general-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be upgraded to `5.21.0`
- `uk.gov.hmrc.bootstrap-common-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) should be changed to test scope - for security

**Comment by platops-general-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- There is a bobby warning for `uk.gov.hmrc.bootstrap-common-play-28` as pulled in by `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9): bobby warning message goes here
- `uk.gov.hmrc.bootstrap-common-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) is not limited to test scope

**Comment by platops-general-labs** [comment]
- System property lookup can be removed in [conf/application-json-logger.xml](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/conf/application-json-logger.xml#L8) - Bootstrap's LoggerModule allows configuration of loggers without this. See README https://github.com/hmrc/bootstrap-play#version-5180
- There is a bobby warning for `uk.gov.hmrc.bootstrap-common-play-28` as pulled in by `uk.gov.hmrc.bootstrap-frontend-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9): bobby warning message goes here
- `uk.gov.hmrc.bootstrap-common-play-28` in [project/AppDependencies.scala](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/AppDependencies.scala#L9) is not limited to test scope

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- ~~`uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)~~

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-general-labs** [comment]
- ~~`uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)~~

**Comment by platops-general-labs** [comment]
- ~~`uk.gov.hmrc.sbt-auto-build` can be updated to `3.6.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)~~

**Comment by platops-pr-bot-labs** [comment]
- Add `addSbtPlugin("uk.gov.hmrc" % "sbt-auto-build" % "3.6.0")` to [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L1)

**Comment by platops-pr-bot-labs** [comment]
- Add `addSbtPlugin("uk.gov.hmrc" % "sbt-auto-build" % "3.6.0")` to [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L1)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Comment by platops-pr-bot-labs** [comment]
- `uk.gov.hmrc.sbt-auto-build` can be updated to `3.8.0` in [project/plugins.sbt](https://github.com/hmrc/platops-example-frontend-microservice/blob/Shnick-patch-1/project/plugins.sbt#L7)

**Pull request closed without merging**
